- name: download
  get_url: >
    url={{ direnv.bin_url }}
    sha256sum={{ direnv.bin_sha256 }}
    dest=/usr/local/bin/direnv
    owner=root
    group=root
    mode=0755
  when: direnv.install_from_sources

- name: install direnv package
  package:
    name: direnv
    state: present
  when: not direnv.install_from_sources

- name: install profile hook
  copy: >
    content='eval "$(direnv hook bash)"'
    dest=/etc/profile.d/direnv.sh
    owner=root
    group=root
    mode=0644
